import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const productsToSync = [
  {
    id: 'prod_001',
    name: 'Rolex Submariner Style',
    nameZh: '劳力士潜航者风格',
    description: 'Classic diving watch with automatic movement and water resistance',
    descriptionZh: '经典潜水腕表，自动机械机芯，防水设计',
    price: 189.00,
    originalPrice: 299.00,
    category: 'Submariner',
    image: '/products/image1.webp',
    images: ['/products/image1.webp', '/products/image2.jpeg'],
    stock: 15,
    isActive: true,
    caseSize: '40mm',
    movement: 'Automatic',
    strap: 'Oyster Bracelet',
    waterResistance: '300m',
  },
  {
    id: 'prod_002',
    name: 'Rolex Datejust Style',
    nameZh: '劳力士日志型风格',
    description: 'Elegant dress watch with date function and fluted bezel',
    descriptionZh: '优雅正装腕表，日期功能，三角坑纹表圈',
    price: 169.00,
    originalPrice: 259.00,
    category: 'Datejust',
    image: '/products/image3.jpeg',
    images: ['/products/image3.jpeg', '/products/image4.jpeg'],
    stock: 12,
    isActive: true,
    caseSize: '36mm',
    movement: 'Automatic',
    strap: 'Jubilee Bracelet',
    waterResistance: '100m',
  },
  {
    id: 'prod_003',
    name: 'Rolex Daytona Style',
    nameZh: '劳力士迪通拿风格',
    description: 'Chronograph sports watch with tachymeter bezel',
    descriptionZh: '计时码表运动腕表，测速表圈',
    price: 199.00,
    originalPrice: 329.00,
    category: 'Daytona',
    image: '/products/image5.jpeg',
    images: ['/products/image5.jpeg', '/products/image6.webp'],
    stock: 8,
    isActive: true,
    caseSize: '40mm',
    movement: 'Automatic Chronograph',
    strap: 'Oyster Bracelet',
    waterResistance: '100m',
  },
  {
    id: 'prod_004',
    name: 'Rolex GMT-Master Style',
    nameZh: '劳力士格林尼治风格',
    description: 'Dual time zone watch with rotating 24-hour bezel',
    descriptionZh: '双时区腕表，旋转24小时表圈',
    price: 179.00,
    originalPrice: 289.00,
    category: 'GMT-Master',
    image: '/products/image7.jpeg',
    images: ['/products/image7.jpeg', '/products/image8.jpeg'],
    stock: 10,
    isActive: true,
    caseSize: '40mm',
    movement: 'Automatic GMT',
    strap: 'Jubilee Bracelet',
    waterResistance: '100m',
  },
  {
    id: 'prod_005',
    name: 'Rolex Explorer Style',
    nameZh: '劳力士探险家风格',
    description: 'Adventure watch with luminous markers and rugged design',
    descriptionZh: '探险腕表，夜光时标，坚固设计',
    price: 159.00,
    originalPrice: 249.00,
    category: 'Explorer',
    image: '/products/image9.jpeg',
    images: ['/products/image9.jpeg', '/products/image10.jpeg'],
    stock: 20,
    isActive: true,
    caseSize: '39mm',
    movement: 'Automatic',
    strap: 'Oyster Bracelet',
    waterResistance: '100m',
  },
  {
    id: 'prod_006',
    name: 'Rolex Yacht-Master Style',
    nameZh: '劳力士游艇名仕风格',
    description: 'Nautical watch with rotatable bezel and regatta countdown',
    descriptionZh: '航海腕表，旋转表圈，帆船赛倒计时',
    price: 189.00,
    originalPrice: 299.00,
    category: 'Yacht-Master',
    image: '/products/image11.jpeg',
    images: ['/products/image11.jpeg', '/products/image12.jpeg'],
    stock: 6,
    isActive: true,
    caseSize: '40mm',
    movement: 'Automatic',
    strap: 'Oysterflex',
    waterResistance: '100m',
  },
  {
    id: 'prod_007',
    name: 'Rolex Oyster Perpetual Style',
    nameZh: '劳力士蚝式恒动风格',
    description: 'Classic time-only watch with clean dial design',
    descriptionZh: '经典三针腕表，简洁表盘设计',
    price: 149.00,
    originalPrice: 229.00,
    category: 'Oyster Perpetual',
    image: '/products/image13.jpeg',
    images: ['/products/image13.jpeg', '/products/image14.jpeg'],
    stock: 25,
    isActive: true,
    caseSize: '36mm',
    movement: 'Automatic',
    strap: 'Oyster Bracelet',
    waterResistance: '100m',
  },
  {
    id: 'prod_008',
    name: 'Rolex Lady-Datejust Style',
    nameZh: '劳力士女装日志型风格',
    description: 'Elegant women watch with diamond markers',
    descriptionZh: '优雅女士腕表，钻石时标',
    price: 169.00,
    originalPrice: 269.00,
    category: 'Lady-Datejust',
    image: '/products/image15.jpeg',
    images: ['/products/image15.jpeg', '/products/image16.jpeg'],
    stock: 18,
    isActive: true,
    caseSize: '28mm',
    movement: 'Automatic',
    strap: 'Jubilee Bracelet',
    waterResistance: '100m',
  },
  {
    id: 'prod_009',
    name: 'Rolex Pearlmaster Style',
    nameZh: '劳力士珍珠淑女型风格',
    description: 'Luxury women watch with precious stone setting',
    descriptionZh: '奢华女士腕表，宝石镶嵌',
    price: 199.00,
    originalPrice: 319.00,
    category: 'Pearlmaster',
    image: '/products/image17.jpeg',
    images: ['/products/image17.jpeg', '/products/image18.jpeg'],
    stock: 5,
    isActive: true,
    caseSize: '29mm',
    movement: 'Automatic',
    strap: 'Pearlmaster Bracelet',
    waterResistance: '100m',
  },
  {
    id: 'prod_010',
    name: 'Rolex Air-King Style',
    nameZh: '劳力士空中霸王风格',
    description: 'Aviation-inspired watch with bold dial',
    descriptionZh: '航空灵感腕表，醒目表盘',
    price: 159.00,
    originalPrice: 239.00,
    category: 'Air-King',
    image: '/products/image19.jpeg',
    images: ['/products/image19.jpeg', '/products/image20.jpeg'],
    stock: 14,
    isActive: true,
    caseSize: '40mm',
    movement: 'Automatic',
    strap: 'Oyster Bracelet',
    waterResistance: '100m',
  },
  {
    id: 'prod_011',
    name: 'Rolex Sea-Dweller Style',
    nameZh: '劳力士海使型风格',
    description: 'Professional diving watch with helium escape valve',
    descriptionZh: '专业潜水腕表，排氦阀门',
    price: 209.00,
    originalPrice: 339.00,
    category: 'Sea-Dweller',
    image: '/products/image21.jpeg',
    images: ['/products/image21.jpeg', '/products/image22.jpeg'],
    stock: 4,
    isActive: true,
    caseSize: '43mm',
    movement: 'Automatic',
    strap: 'Oyster Bracelet',
    waterResistance: '1220m',
  },
  {
    id: 'prod_012',
    name: 'Rolex Milgauss Style',
    nameZh: '劳力士格磁型风格',
    description: 'Anti-magnetic watch with lightning bolt seconds hand',
    descriptionZh: '防磁腕表，闪电形状秒针',
    price: 179.00,
    originalPrice: 279.00,
    category: 'Milgauss',
    image: '/products/image23.jpeg',
    images: ['/products/image23.jpeg', '/products/image24.jpeg'],
    stock: 9,
    isActive: true,
    caseSize: '40mm',
    movement: 'Automatic',
    strap: 'Oyster Bracelet',
    waterResistance: '100m',
  },
  {
    id: 'prod_013',
    name: 'Rolex Cellini Style',
    nameZh: '劳力士切利尼风格',
    description: 'Dress watch with leather strap and moonphase',
    descriptionZh: '正装腕表，皮表带，月相显示',
    price: 189.00,
    originalPrice: 299.00,
    category: 'Cellini',
    image: '/products/image25.jpeg',
    images: ['/products/image25.jpeg', '/products/image26.jpeg'],
    stock: 7,
    isActive: true,
    caseSize: '39mm',
    movement: 'Automatic',
    strap: 'Leather',
    waterResistance: '50m',
  },
  {
    id: 'prod_014',
    name: 'Rolex Sky-Dweller Style',
    nameZh: '劳力士纵航者风格',
    description: 'Annual calendar watch with dual time zone',
    descriptionZh: '年历腕表，双时区显示',
    price: 219.00,
    originalPrice: 359.00,
    category: 'Sky-Dweller',
    image: '/products/image27.jpeg',
    images: ['/products/image27.jpeg', '/products/image28.jpeg'],
    stock: 3,
    isActive: true,
    caseSize: '42mm',
    movement: 'Automatic Annual Calendar',
    strap: 'Oyster Bracelet',
    waterResistance: '100m',
  },
  // 测试商品
  {
    id: 'prod_015',
    name: 'TEST PRODUCT - DO NOT BUY',
    nameZh: '测试商品 - 请勿购买',
    description: 'This is a test product for development purposes only. Do not purchase.',
    descriptionZh: '这是仅供开发测试使用的商品。请勿购买。',
    price: 1.00,
    originalPrice: 1.00,
    category: 'Test',
    image: '/products/image1.webp',
    images: ['/products/image1.webp'],
    stock: 999,
    isActive: true,
    caseSize: '40mm',
    movement: 'Quartz',
    strap: 'Test',
    waterResistance: '0m',
  },
];

async function syncProducts() {
  console.log('开始同步商品数据到数据库...\n');
  
  for (const product of productsToSync) {
    try {
      await prisma.product.upsert({
        where: { id: product.id },
        update: {
          name: product.name,
          nameZh: product.nameZh,
          description: product.description,
          descriptionZh: product.descriptionZh,
          price: product.price,
          originalPrice: product.originalPrice,
          category: product.category,
          image: product.image,
          images: product.images,
          stock: product.stock,
          isActive: product.isActive,
          caseSize: product.caseSize,
          movement: product.movement,
          strap: product.strap,
          waterResistance: product.waterResistance,
        },
        create: product,
      });
      console.log(`✅ ${product.name} (${product.id})`);
    } catch (error) {
      console.error(`❌ ${product.name} (${product.id}):`, (error as Error).message);
    }
  }
  
  console.log(`\n🎉 同步完成！共 ${productsToSync.length} 个商品`);
  
  // 统计
  const count = await prisma.product.count();
  console.log(`📊 数据库当前共有 ${count} 个商品`);
}

syncProducts()
  .catch((e) => {
    console.error('同步失败:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
