import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const productsToSync = [
  {
    id: 'prod_001',
    name: 'Rolex Submariner Style',
    nameZh: '劳力士潜航者风格',
    price: 189.00,
    originalPrice: 299.00,
    brand: 'Rolex',
    category: 'Submariner',
    image: '/products/image1.webp',
    detailImage1: '/products/image2.jpeg',
    stock: 15,
    isActive: true,
    caseMaterial: 'Stainless Steel',
    dial: 'Black',
    movement: 'Automatic',
    powerReserve: '72 hours',
    functions: 'Date',
  },
  {
    id: 'prod_002',
    name: 'Rolex Datejust Style',
    nameZh: '劳力士日志型风格',
    price: 169.00,
    originalPrice: 259.00,
    brand: 'Rolex',
    category: 'Datejust',
    image: '/products/image3.jpeg',
    detailImage1: '/products/image4.jpeg',
    stock: 12,
    isActive: true,
    caseMaterial: 'Stainless Steel',
    dial: 'Blue',
    movement: 'Automatic',
    powerReserve: '70 hours',
    functions: 'Date',
  },
  {
    id: 'prod_003',
    name: 'Rolex Daytona Style',
    nameZh: '劳力士迪通拿风格',
    price: 199.00,
    originalPrice: 329.00,
    brand: 'Rolex',
    category: 'Daytona',
    image: '/products/image5.jpeg',
    detailImage1: '/products/image6.webp',
    stock: 8,
    isActive: true,
    caseMaterial: 'Stainless Steel',
    dial: 'White',
    movement: 'Automatic Chronograph',
    powerReserve: '72 hours',
    functions: 'Chronograph, Tachymeter',
  },
  {
    id: 'prod_004',
    name: 'Rolex GMT-Master Style',
    nameZh: '劳力士格林尼治风格',
    price: 179.00,
    originalPrice: 289.00,
    brand: 'Rolex',
    category: 'GMT-Master',
    image: '/products/image7.jpeg',
    detailImage1: '/products/image8.jpeg',
    stock: 10,
    isActive: true,
    caseMaterial: 'Stainless Steel',
    dial: 'Black',
    movement: 'Automatic GMT',
    powerReserve: '70 hours',
    functions: 'GMT, Date',
  },
  {
    id: 'prod_005',
    name: 'Rolex Explorer Style',
    nameZh: '劳力士探险家风格',
    price: 159.00,
    originalPrice: 249.00,
    brand: 'Rolex',
    category: 'Explorer',
    image: '/products/image9.jpeg',
    detailImage1: '/products/image10.jpeg',
    stock: 20,
    isActive: true,
    caseMaterial: 'Stainless Steel',
    dial: 'Black',
    movement: 'Automatic',
    powerReserve: '72 hours',
    functions: 'Hour, Minute, Second',
  },
  {
    id: 'prod_006',
    name: 'Rolex Yacht-Master Style',
    nameZh: '劳力士游艇名仕风格',
    price: 189.00,
    originalPrice: 299.00,
    brand: 'Rolex',
    category: 'Yacht-Master',
    image: '/products/image11.jpeg',
    detailImage1: '/products/image12.jpeg',
    stock: 10,
    isActive: true,
    caseMaterial: 'Stainless Steel',
    dial: 'Blue',
    movement: 'Automatic',
    powerReserve: '70 hours',
    functions: 'Date',
  },
  {
    id: 'prod_007',
    name: 'Rolex Day-Date Style',
    nameZh: '劳力士星期日历风格',
    price: 209.00,
    originalPrice: 349.00,
    brand: 'Rolex',
    category: 'Day-Date',
    image: '/products/image13.jpeg',
    detailImage1: '/products/image14.jpeg',
    stock: 6,
    isActive: true,
    caseMaterial: 'Gold Plated',
    dial: 'Champagne',
    movement: 'Automatic',
    powerReserve: '72 hours',
    functions: 'Day, Date',
  },
  {
    id: 'prod_008',
    name: 'Rolex Milgauss Style',
    nameZh: '劳力士格磁型风格',
    price: 175.00,
    originalPrice: 279.00,
    brand: 'Rolex',
    category: 'Milgauss',
    image: '/products/image15.jpeg',
    detailImage1: '/products/image16.jpeg',
    stock: 14,
    isActive: true,
    caseMaterial: 'Stainless Steel',
    dial: 'Black',
    movement: 'Automatic',
    powerReserve: '72 hours',
    functions: 'Hour, Minute, Second',
  },
  {
    id: 'prod_009',
    name: 'Rolex Air-King Style',
    nameZh: '劳力士空中霸王风格',
    price: 149.00,
    originalPrice: 229.00,
    brand: 'Rolex',
    category: 'Air-King',
    image: '/products/image17.jpeg',
    detailImage1: '/products/image18.jpeg',
    stock: 18,
    isActive: true,
    caseMaterial: 'Stainless Steel',
    dial: 'Black',
    movement: 'Automatic',
    powerReserve: '72 hours',
    functions: 'Hour, Minute, Second',
  },
  {
    id: 'prod_010',
    name: 'Rolex Sea-Dweller Style',
    nameZh: '劳力士海使型风格',
    price: 219.00,
    originalPrice: 359.00,
    brand: 'Rolex',
    category: 'Sea-Dweller',
    image: '/products/image19.jpeg',
    detailImage1: '/products/image20.jpeg',
    stock: 7,
    isActive: true,
    caseMaterial: 'Stainless Steel',
    dial: 'Black',
    movement: 'Automatic',
    powerReserve: '70 hours',
    functions: 'Date',
  },
  {
    id: 'prod_011',
    name: 'Rolex Sky-Dweller Style',
    nameZh: '劳力士纵航者风格',
    price: 249.00,
    originalPrice: 399.00,
    brand: 'Rolex',
    category: 'Sky-Dweller',
    image: '/products/image21.jpeg',
    detailImage1: '/products/image22.jpeg',
    stock: 5,
    isActive: true,
    caseMaterial: 'Gold Plated',
    dial: 'Champagne',
    movement: 'Automatic Annual Calendar',
    powerReserve: '72 hours',
    functions: 'Annual Calendar, GMT',
  },
  {
    id: 'prod_012',
    name: 'Rolex Cellini Style',
    nameZh: '劳力士切利尼风格',
    price: 199.00,
    originalPrice: 319.00,
    brand: 'Rolex',
    category: 'Cellini',
    image: '/products/image23.jpeg',
    detailImage1: '/products/image24.jpeg',
    stock: 9,
    isActive: true,
    caseMaterial: 'Gold Plated',
    dial: 'White',
    movement: 'Manual',
    powerReserve: '48 hours',
    functions: 'Hour, Minute',
  },
  {
    id: 'prod_013',
    name: 'Rolex Lady-Datejust Style',
    nameZh: '劳力士女装日志型风格',
    price: 159.00,
    originalPrice: 249.00,
    brand: 'Rolex',
    category: 'Lady-Datejust',
    image: '/products/image25.jpeg',
    detailImage1: '/products/image26.jpeg',
    stock: 22,
    isActive: true,
    caseMaterial: 'Stainless Steel',
    dial: 'Pink',
    movement: 'Automatic',
    powerReserve: '55 hours',
    functions: 'Date',
  },
  {
    id: 'prod_014',
    name: 'Rolex Pearlmaster Style',
    nameZh: '劳力士珍珠淑女型风格',
    price: 229.00,
    originalPrice: 369.00,
    brand: 'Rolex',
    category: 'Pearlmaster',
    image: '/products/image27.jpeg',
    detailImage1: '/products/image28.jpeg',
    stock: 4,
    isActive: true,
    caseMaterial: 'Rose Gold',
    dial: 'Mother of Pearl',
    movement: 'Automatic',
    powerReserve: '55 hours',
    functions: 'Date',
  },
];

async function syncProducts() {
  console.log('开始同步商品数据到数据库...\n');

  for (const product of productsToSync) {
    try {
      await prisma.product.upsert({
        where: { id: product.id },
        update: {
          name: product.name,
          nameZh: product.nameZh,
          price: product.price,
          originalPrice: product.originalPrice,
          brand: product.brand,
          category: product.category,
          image: product.image,
          detailImage1: product.detailImage1,
          stock: product.stock,
          isActive: product.isActive,
          caseMaterial: product.caseMaterial,
          dial: product.dial,
          movement: product.movement,
          powerReserve: product.powerReserve,
          functions: product.functions,
        },
        create: product,
      });
      console.log(`✅ ${product.name} (${product.id})`);
    } catch (error) {
      console.error(`❌ ${product.name} (${product.id}):`, (error as Error).message);
    }
  }

  console.log(`\n🎉 同步完成！共 ${productsToSync.length} 个商品`);

  // 统计
  const count = await prisma.product.count();
  console.log(`📊 数据库当前共有 ${count} 个商品`);
}

syncProducts()
  .catch((e) => {
    console.error('同步失败:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
